spring:
  application:
    name: find-friend-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lyx
  # session失效时间 60*60*24=86400
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 8180
  servlet:
    context-path: /api
  reactive:
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.lyx.usercenter.controller
